version: '3'
services:
  node_1:
    image: quorum
    volumes:
      - './test_task/qdata_1:/qdata'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.2'
    ports:
      - 22001:8545
    user: '1000:1000'
  node_2:
    image: quorum
    volumes:
      - './test_task/qdata_2:/qdata'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.3'
    ports:
      - 22002:8545
    user: '1000:1000'
  node_3:
    image: quorum
    volumes:
      - './test_task/qdata_3:/qdata'
    networks:
      quorum_net:
        ipv4_address: '172.13.0.4'
    ports:
      - 22003:8545
    user: '1000:1000'

  python_client:
    build: ./python_client
    volumes:
      - './python_client/src:/src'
    networks:
      - quorum_net
    ports:
      - 8000:8000
    depends_on:
      - node_1

networks:
  quorum_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.0.0/16
